name:                tennis-haskell
version:             0.1.0.0
github:              "craigjbass/tennis-haskell"
license:             BSD3
author:              "Craig J. Bass"
maintainer:          "craig@madetech.com  "
copyright:           "2018 Craig J. Bass"

extra-source-files:
- README.md

description: Tennis Kata 

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tennis-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-haskell

tests:
  tennis-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-haskell
    - hspec
